module PagSeguro
  class Errors
  	def self.get_errors(xml)
      errors = []
      if xml == 'Unauthorized'
      	errors << 'Não Autorizado' 
      else
	      xml.css("errors > error").each do |error|
	        errors << get_translate_error(error.css("code").text)
	      end
	    end
      errors
    end

  	def self.get_translate_error(code)
      case code
      when "10001"
        "O parâmetro email deve ser informado."
      when "10002"
        "O parâmetro token deve ser informado."
      when "10003"
        "O valor informado no parâmetro email é inválido."
      when "11001"
        "O parâmetro receiverEmail deve ser informado."
      when "11002"
        "O tamanho do valor informado no parâmetro receiverEmail é inválido."
      when "11003"
        "O valor informado no parâmetro receiverEmail é inválido."
      when "11004"
        "O parâmetro currency deve ser informado."
      when "11005"
        "O valor informado no parâmetro currency é inválido."
      when "11006"
        "O tamanho do valor informado no parâmetro redirectURL é inválido."
      when "11007"
        "O valor informado no parâmetro redirectURL é inválido."
      when "11008"
        "O tamanho do valor informado no parâmetro reference é inválido."
      when "11009"
        "O tamanho do valor informado no parâmetro senderEmail é inválido."
      when "11010"
        "O valor informado no parâmetro senderEmail é inválido."
      when "11011"
        "O tamanho do valor informado no parâmetro senderName é inválido."
      when "11012"
        "O valor informado no parâmetro senderName é inválido."
      when "11013"
        "O valor informado no parâmetro senderAreaCode é inválido."
      when "11014"
        "O valor informado no parâmetro senderPhone é inválido."
      when "11015"
        "O parâmetro shippingType deve ser informado."
      when "11016"
        "O tipo definido no parâmetro shippingType é inválido."
      when "11017"
        "O valor informado no parâmetro Endereço:Cep é inválido."
      when "11018"
        "O tamanho do valor informado no parâmetro Endereço:Rua é inválido."
      when "11019"
        "O tamanho do valor informado no parâmetro Endereço:Número é inválido."
      when "11020"
        "O tamanho do valor informado no parâmetro Endereço:Complemento é inválido."
      when "11021"
        "O tamanho do valor informado no parâmetro Endereço:Bairro é inválido."
      when "11022"
        "O tamanho do valor informado no parâmetro Endereço:Cidade é inválido."
      when "11023"
        "O formato do valor informado no parâmetro Endereço:Estado é inválido."
      when "11024"
        "O valor informado no parâmetro itemQuantity é inválido."
      when "11025"
        "O parâmetro itemId deve ser informado."
      when "11026"
        "O parâmetro itemQuantity deve ser informado."
      when "11027"
        "O valor informado no parâmetro itemQuantity é inválido."
      when "11028"
        "O parâmetro itemAmount deve ser informado."
      when "11029"
        "O formato do valor informado no parâmetro itemAmount é inválido."
      when "11030"
        "O valor informado no parâmetro itemAmount é inválido."
      when "11031"
        "O formato do valor informado no parâmetro itemShippingCost é inválido."
      when "11032"
        "O valor informado no parâmetro itemShippingCost é inválido."
      when "11033"
        "O parâmetro itemDescription deve ser informado."
      when "11034"
        "O tamanho do valor informado no parâmetro itemDescription é inválido."
      when "11035"
        "O valor informado no parâmetro itemWeight é inválido."
      when "11036"
        "O formato do valor informado no parâmetro extraAmount é inválido."
      when "11037"
        "O valor informado no parâmetro extraAmount é inválido."
      when "11038"
        "Valor não autorizado para receiverEmail."
      when "11039"
        "A estrutura do xml está incorreta."
      when "11040"
        "O formato do valor informado no parâmetro maxAge é inválido."
      when "11041"
        "O valor informado no parâmetro maxAge é inválido."
      when "11042"
        "O formato do valor informado no parâmetro maxUses é inválido."
      when "11043"
        "O valor informado no parâmetro maxUses é inválido."
      when "11044"
        "O parâmetro initialDate deve ser informado."
      when "11045"
        "O valor informado no parâmetro initialDate deve ser inferior ou igual a data atual."
      when "11046"
        "O valor informado no parâmetro initialDate não pode ser anterior a 180 dias contados da data atual."
      when "11047"
        "O valor informado no parâmetro initialDate deve ser menor ou igual ao valor informado no parâmetro finalDate."
      when "11048"
        "O intervalo entre os parâmetros initialDate e finalDate deve ser inferior ou igual a 30 dias."
      when "11049"
        "O valor informado no parâmetro finalDate deve ser inferior ou igual a data atual."
      when "11050"
        "O valor informado no parâmetro initialDate é inválido. O formato correto é yyyy-MM-ddTHH:mm."
      when "11051"
        "O valor informado no parâmetro finalDate é inválido. O formato correto é yyyy-MM-ddTHH:mm."
      when "11052"
        "O valor informado no parâmetro page é inválido. Utilize um inteiro maior que 0."
      when "11053"
        "O valor informado no parâmetro maxPageResults deve ser entre 1 e 1000."
      when "11104"
        "A soma dos produto menos o desconto, não deve ser inferior ou igual a 0."
      when "11105"
        "O valor total do checkout é inválido."
      when "11111"
        "O valor informado no parâmetro shippingCost é inválido."
      when "11112"
        "O formato do valor informado no parâmetro shippingCost é inválido."
      when "11164"
        "O valor informado no parâmetro senderCPF é inválido."
      when "13001"
        "O código de notificação informado é inválido."
      when "13002"
        "O código da transação deve ser informado."
      when "13003"
        "O código de transação informado é inválido."
      when "13004"
        "O parâmetro initialDate deve ser informado"
      when "13005"
        "O valor informado no parâmetro initialDate deve ser inferior ou igual a data atual."
      when "13006"
        "O valor informado no parâmetro initialDate não pode ser anterior a 180 dias contados da data atual."
      when "13007"
        "O valor informado no parâmetro initialDate deve ser menor ou igual ao valor informado no parâmetro finalDate."
      when "13008"
        "O intervalo entre os parâmetros initialDate e finalDate deve ser inferior ou igual a 30 dias."
      when "13009"
        "O valor informado no parâmetro finalDate deve ser inferior ou igual a data atual."
      when "13010"
        "O valor informado no parâmetro initialDate é inválido. O formato correto é yyyy-MM-ddTHH:mm."
      when "13011"
        "O valor informado no parâmetro finalDate é inválido. O formato correto é yyyy-MM-ddTHH:mm."
      when "13012"
        "O valor informado no parâmetro initialDate deve ser inferior a."
      when "13013"
        "O valor informado no parâmetro page é inválido. Utilize um inteiro maior que 0."
      when "13014"
        "O valor informado no parâmetro maxPageResults deve ser entre 1 e 1000."
      when "13015"
        "Transação não encontrada."
      when "13020"
        "O valor informado no parâmetro page é superior a quantidade de páginas retornadas."
      when "13021"
        "Esta consulta não pode ser realizada pois o status da transação requisitada é inválido."
      else
        code
      end
    end
  end
end